#!/bin/sh
 
# define default return code as 0
rc=0
curl -o /dev/null -sSf http://{{sys.ip}}:8080/national-parks
case $? in
  0)
    rc=1 ;;
  3)
    rc=0 ;;
  4)
    rc=2 ;;
  *)
    rc=3 ;;
esac
 
exit $rc
