version: '2'
services:
  mongodb:
    image: core/mongodb:3.2.10-20171016003652
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''" 
      HAB_LICENSE: "accept-no-persist"
  national-parks:
    image: nrycar/national-parks:latest
    depends_on:
      - "mongodb"
    command: --peer mongodb --bind database:mongodb.default
    environment:
      HAB_LICENSE: "accept-no-persist"
  haproxy:
    image: nrycar/haproxy:latest
    depends_on: 
      - "national-parks"
    command: --peer national-parks --bind backend:national-parks.default
    ports:
      - 8085:8085
      - 9631:9631
      - 8000:8000
    environment:
      HAB_HAPROXY: "maxconn = '32'\nhttpchk = 'GET /national-parks'\n[front-end]\nlisten = '*'\nport = '8085'\nmode = 'http'\n[status]\nenabled = true\nlisten = '*'\nport = '8000'\nuser = 'admin'\npassword = 'password'\nuri = '/haproxy-stats'"
      HAB_LICENSE: "accept-no-persist"
